[MODIFY] cosegu -> recruit 기능으로 수정
wecode-bootcamp-korea/37-2nd-Cosegu-backend pull request #5
Opened 2022-10-07 05:20 UTC by walter811

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 구인공고 불러오기 기능 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 전체 및 코세구 크루 구인공고를 불러오는 기능 구현
- 기존 코세구 크루의 모집공고만을 불러왔던 API를 전체 모집 공고까지 불러올 수 있도록 하나로 통합

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-10-07 06:08 UTC, bigfanoftim requested changes
cosegu -> recruit 로 수정하셨으면 이전에 작성하신 cosegu는 전부 지워주세요!

2022-10-07 06:52 UTC, walter811 commented
> cosegu -> recruit 로 수정하셨으면 이전에 작성하신 cosegu는 전부 지워주세요!

PR 할때 전부 삭제하고 올렸는데 혹시 메인에서 직접 삭제해야 하나요?

2022-10-07 07:59 UTC, bigfanoftim commented
> > cosegu -> recruit 로 수정하셨으면 이전에 작성하신 cosegu는 전부 지워주세요!
> 
> PR 할때 전부 삭제하고 올렸는데 혹시 메인에서 직접 삭제해야 하나요?

그럴리가요! 해당 브랜치가 맞는지 한번 제대로 확인해보셔야 할 것 같습니다. 혹은 수정된게 제대로 푸시된 것이 맞는지도 확인 부탁드립니다.

2022-10-07 08:00 UTC, bigfanoftim commented
<img width="657" alt="image" src="https://user-images.githubusercontent.com/62135254/194503261-78726a8a-a99f-46bc-8f0f-1c99c5cc28d2.png">

PR 올리시고 꼭 Files changed 확인해보세요!

2022-10-07 08:36 UTC, walter811 commented
> <img alt="image" width="657" src="https://user-images.githubusercontent.com/62135254/194503261-78726a8a-a99f-46bc-8f0f-1c99c5cc28d2.png">
> 
> PR 올리시고 꼭 Files changed 확인해보세요!

아아 제가 말을 좀 잘못한 것 같습니다! 
코세구 크루 페이지가 사라진게 아니라서 코세구 크루용 모집공고를 불러오는 기존 코드에 
일반 지원하기 페이지의 모집공고를 불러오는 코드를 더해 서 recruit로 이름을 바꾼 것입니다!
그래서 해당 코드는 의도한 것이 맞습니다! 혼동을 드려 죄송합니다

2022-10-11 02:10 UTC, bigfanoftim requested changes
리뷰 확인하시고 전체적으로 수정해 주세요!

2022-10-11 02:10 UTC, bigfanoftim commented on api/controllers/recruitController.js
> +const getCoseguRecruit = asyncWrap(async(req, res) => {
모델링 리뷰때 말씀드린 것처럼 어차피 categoryId를 받으면 되기 때문에 cosegu인지 아닌지는 구분하실 필요가 없을 것 같아요.

2022-10-11 02:10 UTC, bigfanoftim commented on api/models/recruitDao.js
> +        )as a
```suggestion
        ) as does_exist
```
a 보다는 명확한 네이밍이 좋을 것 같아요.

2022-10-11 02:10 UTC, bigfanoftim commented on api/models/recruitDao.js
> +                GROUP_CONCAT(t.name SEPARATOR '\n') as tagName
여러 태그를 한번에 처리하려고 이렇게 작성하신 건가요?
만약 문자열 합치기를 의도하신거라면 MySQL에서 지원하는 [JSON aggregation functions](https://dev.mysql.com/worklog/task/?id=7987) 를 활용해 보세요!

2022-10-11 02:10 UTC, bigfanoftim commented on api/models/recruitDao.js
> +        ) as a
말씀드린대로 Json을 활용하면 as a 와 같은 구문이 필요없어질거에요!

2022-10-11 02:10 UTC, bigfanoftim commented on api/models/recruitDao.js
> +const getByCategoryId = async(categoryId, limit, offset) => {
```suggestion
const getRecruitsByCategoryId = async(categoryId, limit, offset) => {
```
명확한 네이밍이 필요해 보입니다.

2022-10-11 02:59 UTC, walter811 commented on api/models/recruitDao.js
> +        ) as a
넵 해당 사항 반영해서 수정했는데 카테고리별로 가져올 경우(getByCategoryId)에는 잘 나오지만 태그아이디를 추가해 필터링할 경우(getByTagId) 전체 태그 데이터를 가져오지 못하고 선택한 태그만 가져오는데 어떻게 해결하면 좋을까요?

2022-10-11 03:12 UTC, bigfanoftim commented on api/models/recruitDao.js
> +        ) as a
전체적으로 수정한 코드 한번 푸시해주세요!

2022-10-11 03:22 UTC, walter811 commented on api/models/recruitDao.js
> +        ) as a
넵! getByTagId도 일단 수정해서 보내드리겠습니다 :)

2022-10-11 04:21 UTC, bigfanoftim requested changes

2022-10-11 04:21 UTC, bigfanoftim commented on db/migrations/20221005070042_users.sql
>      PRIMARY KEY (id)
여긴 갑자기 migration이 추가가 되었네요. 확인 후 지워주세요!

2022-10-11 04:21 UTC, bigfanoftim commented on api/models/recruitDao.js
> +        INNER JOIN companies as com ON com.id = r.company_id
```suggestion
```
불필요한 조인인것 같으니 지워주세요!

2022-10-11 04:21 UTC, bigfanoftim commented on api/models/recruitDao.js
> +        INNER JOIN companies as com ON com.id = r.company_id
```suggestion
```
여기도 마찬가지 입니다.

2022-10-11 04:48 UTC, walter811 commented on db/migrations/20221005070042_users.sql
>      PRIMARY KEY (id)
> 여긴 갑자기 migration이 추가가 되었네요. 확인 후 지워주세요!

DB 변경사항이 생겨 migration을 수정했는데 이렇게 하면 문제가 있는걸까요?

2022-10-12 04:23 UTC, bigfanoftim approved these changes
LGTM 👍

2022-10-12 04:23 UTC, merged