소셜로그인 및 jwt발급 완료
wecode-bootcamp-korea/37-2nd-Cosegu-backend pull request #6
Opened 2022-10-11 03:49 UTC by kyunambae

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 소셜 로그인(네이버) 후 서버 jwt 토큰 발급  

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 소셜로그인(네이버) 구현
- 로그인 후, 유저 정보를 가져와 데이터베이스에 재 가공하여 저장
- 이후 jwt 토큰 발급 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-10-11 04:07 UTC, bigfanoftim commented
라벨 변경 전 PR 상태를 파악해 주세요.

2022-10-11 04:26 UTC, kyunambae commented
conflict 해결하였습니다.

2022-10-11 04:51 UTC, bigfanoftim requested changes

2022-10-11 04:51 UTC, bigfanoftim commented on api/services/userService.js
> +    });
```suggestion
  const kakaoAccessToken = await axios
    .post(
      `https://nid.naver.com/oauth2.0/token`,
      qs.stringify({
        grant_type: 'authorization_code',
        client_id: 'M7RqsEOvkI7Fb33qpPnq',
        client_secret: 'p87VetJeBY',
        state: 'cosegu',
        code: code,
      }),
      {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
        },
      }
    ).data.access_token;

  const userInfo = await axios
    .get('https://openapi.naver.com/v1/nid/me', {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
        Authorization: `Bearer ${ACCESS_TOKEN}`,
      },
    }).data.response;
```
이렇게 작성하시면 콜백으로 작성하는 것보다 가독성이 더 좋습니다. 자세한 네이밍은 직접 테스트해보시면서 수정해 주세요!

2022-10-11 04:51 UTC, bigfanoftim commented on api/services/userService.js
> +  //console.log(result);
```suggestion
```

2022-10-11 11:41 UTC, kyunambae commented
수정완료 하였습니다

2022-10-12 03:13 UTC, bigfanoftim approved these changes
LGTM 👍

2022-10-12 03:13 UTC, merged